version: '3'
services:
  web:
    container_name: docker-node
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
    env_file:
      - .env
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    env_file:
      - .env